name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - dev/**
  workflow_dispatch:

# ТУТ  ДОБАВИТЬ АВТОРИЗАЦИЮ ПО ТОКЕНУ OIDC

jobs:
  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./dev

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ADMIN_ACCESS_ARN}}
        aws-region: ${{secrets.AWS_DEFAULT_REGION }} 

    - name: Download plan artifact
      uses: actions/download-artifact@v4
      with: 
        name: tfplan
        path: dev/

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.12.1
    - name: Terraform Init
      run: terraform init -input=false

    - name: terraform apply
      run: terraform apply -auto-approve -input=false tfplan
    

